using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace eBookingComplete.Models
{
    public class BookingDetail
    {
        public string Parametername { get; set; }
        public string ParamValueStr { get; set; }
        public string ApiName { get; set; }
        public int IsValid { get; set; }
        public string ErrorMessage { get; set; }
        public int IsClassified { get; set; }
        public string AdtypeId { get; set; }
        public string CategoryId { get; set; }
        public string AdtypeId1 { get; set; }
        public string AdtypeId2 { get; set; }
        public string AdtypeId3 { get; set; }
        public string AdtypeId4 { get; set; }
        public string Adsizeid { get; set; }
        public string Adsize { get; set; }
        public string AdsizeHeight { get; set; }
        public string AdsizeWidth { get; set; }
        public string Billablesize { get; set; }
        public string BillableHeight { get; set; }
        public string BillableWidth { get; set; }
        public string CardRate { get; set; }
        public string CardAmount { get; set; }
        public string PreVATAmount { get; set; }
        public string VATAmount { get; set; }
        public string Receivable { get; set; }
        public string TotalReceivable { get; set; }
        public string ReceivableAmount { get; set; }
        public string VATPer { get; set; }
        public string RateCardID { get; set; }
        public string AdRateID { get; set; }
        public string AgreedRate { get; set; }
        public string AgreedAmount { get; set; }
        public string AgreedDiscAmount { get; set; }
        public string AgreedDiscPer { get; set; }
        public string PEID { get; set; }
        public Int64 ROID { get; set; }
        public Int64 BookingID { get; set; }
        public Int64 ReceiptID { get; set; }
        public Int64 SourceROID { get; set; }
        public int InsNum { get; set; }
        public int ReleaseID { get; set; }
        public int OrderLevel { get; set; }
        public string PackageID { get; set; }
        public string PkgIDs { get; set; }
        public int RevenueCentreID { get; set; }
        public int BookingCentreID { get; set; }
        public string Premiaid { get; set; }
        public string Colorid { get; set; }
        public string DateSelected { get; set; }
        public int UserId { get; set; }
        public string UserMailID { get; set; }
        public string UserName { get; set; }
        public string CentreName { get; set; }
        public string UserMobile { get; set; }
        public int TotalOrders { get; set; }
        public string OrderNumber { get; set; }
        public string UniqueCode { get; set; }
        public int AgencyID { get; set; }
        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public string ClientVatNum { get; set; }
        public int CanvassorID { get; set; }
        public int ProductID { get; set; }
        public string UOMID { get; set; }
        public int SMEID { get; set; }
        public int BrandID { get; set; }
        public string MaterialSource { get; set; }
        public string MaterialType { get; set; }
        public int ROType { get; set; }
        public int BillType { get; set; }
        public string BoxTypeID { get; set; }
        public string BoxAddress { get; set; }
        public string RONumber { get; set; }
        public int CustomerTypeID { get; set; }
        public int PaymentTypeID { get; set; }
        public int IsManualBilling { get; set; }
        public double ReceiptAmount { get; set; }
        public double WriteoffAmount { get; set; }
        public int PaymentModeID { get; set; }
        public int PaymentModeID1 { get; set; }
        public int PaymentModeID2 { get; set; }
        public string ChequeNumber { get; set; }
        public string ChequeNumber1 { get; set; }
        public string ChequeNumber2 { get; set; }
        public string ChequeDate { get; set; }
        public double Amount { get; set; }
        public double Amount1 { get; set; }
        public double Amount2 { get; set; }
        public int BankID { get; set; }
        public int BankID1 { get; set; }
        public int BankID2 { get; set; }
        public int BankNameID { get; set; }
        public int BankNameID1 { get; set; }
        public int BankNameID2 { get; set; }
        public string BankName { get; set; }
        public string BankName1 { get; set; }
        public string BankName2 { get; set; }
        public string BranchBankName { get; set; }
        public string BranchBankName1 { get; set; }
        public string BranchBankName2 { get; set; }
        public string BranchName { get; set; }
        public string BranchName1 { get; set; }
        public string BranchName2 { get; set; }
        public int BranchID { get; set; }
        public string BankBranchCode { get; set; }
        public string ScheduledDate { get; set; }
        public string ExtraChargesPer { get; set; }
        public string ExtraChargesAmount { get; set; }
        public string ExtraDiscPer { get; set; }
        public string ExtraDiscAmount { get; set; }
        public string ExtraBoxChargesPer { get; set; }
        public string ExtraBoxChargesAmount { get; set; }
        public string AgencyCommissionPer { get; set; }
        public string AgencyCommissionAmount { get; set; }
        public int ROStatus { get; set; }
        public string Status { get; set; }
        public string AuditStatus { get; set; }
        public string AdText { get; set; }
        public int IsCD { get; set; }
        public int IsLogo { get; set; }
        public int StyleSheetID { get; set; }
        public string TotalWords { get; set; }
        public string CharCount { get; set; }
        public string SchemeID { get; set; }
        public string SchemeDetailID { get; set; }
        public int RateFieldChanged { get; set; }
        public int ItemRateFieldChanged { get; set; }
        public string AdColumnSize { get; set; }
        public string Gutter { get; set; }
        public string BillingIns { get; set; }
        public string SchedulingIns { get; set; }
        public string ProdInstructions { get; set; }
        public string Caption { get; set; }
        public int BackdateID { get; set; }
        public int Backdatedays { get; set; }
        public string CasualClientName { get; set; }
        public string CasualClientAddress { get; set; }
        public string ContactPerson { get; set; }
        public string CasualClientCity { get; set; }
        public string CasualClientZipCode { get; set; }
        public string CasualClientPhoneNo { get; set; }
        public string CasualContactPerson { get; set; }
        public string CasualClientNicNumber { get; set; }
        public string CasualClientVatNumber { get; set; }
        public string CasualClientEmailID { get; set; }
        public string CasualClientPassword { get; set; }
        public int CancelReasonID { get; set; }
        public string CancelRemarks { get; set; }
        public int SuspendReasonID { get; set; }
        public string SuspendRemarks { get; set; }
        public string CancelReceiptDate { get; set; }
        public string CancelReceiptRemark { get; set; }
        public int SaveFlag { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string BookingDate { get; set; }
        public string TotalRecordReturn { get; set; }
        public string MBodyChange { get; set; }
        public string MachineID { get; set; }
        public string MachineName { get; set; }
        public string FileNames { get; set; }
        public string MaterialID { get; set; }
        public int MBodyCount { get; set; }
        public string UnConfirmReason { get; set; }
        public string LogoHeight { get; set; }
        public string FilePath { get; set; }
        public string JobSequence { get; set; }
        public string RoFileName { get; set; }
        public string RoFileType { get; set; }
        public string RoFileTitle { get; set; }
        public string FileLength { get; set; }
        public string ClassifiedCol { get; set; }
        public string SearchAgencyName { get; set; }
        public string SearchAgencyCode { get; set; }
        public string SearchAgencyCategory { get; set; }
        public string SearchAgencyCity { get; set; }
        public string SearchAgencyAddress { get; set; }
        public string SearchAgencyType { get; set; }
        public string SearchClientName { get; set; }
        public string SearchClientID { get; set; }
        public string SearchClientCity { get; set; }
        public string SearchClientAddress { get; set; }
        public string SearchClientOldCode { get; set; }
        public int CheckDifferValue { get; set; }
        public string AdvanceAmount { get; set; }
        public string AdvanceReceiptID { get; set; }
        public string AdvanceUtilised { get; set; }
        public string AdvanceAmount1 { get; set; }
        public string AdvanceReceiptID1 { get; set; }
        public string AdvanceUtilised1 { get; set; }
        public string AdvanceAmount2 { get; set; }
        public string AdvanceReceiptID2 { get; set; }
        public string AdvanceUtilised2 { get; set; }
        public string PendingROID { get; set; }
        public int RevisionNumber { get; set; }
        public Int64 LocalROID { get; set; }
        public int CloudOrderStatus { get; set; }

        public List<GridObject>  list { get; set; }
        public BookingDetail()
        {
            list = new List<GridObject>();
        }
    }
}